[package]
name = "libsyncast"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
crossterm = "0.28.1"
feed-rs = "2.3.1"
quick-xml = "0.37.2"
ratatui = "0.29.0"
reqwest = { version = "0.12.12", features = ["blocking"] }
